language: java

script:
  - cd aula-01/java && mvn clean test verify -P cobertura
  - cd aula-01/java && mvn checkstyle:check pmd:check spotbugs:check
 
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - oraclejdk8
