language: java

script:
  - cd aula-01/java && mvn test checkstyle:check spotbugs:check verify -P cobertura
  - cd ../../aula-07/vetor/java && mvn clean test verify -P cobertura && mvn checkstyle:check spotbugs:check
  - cd ../../../aula-08/inteiro && mvn clean test verify -P cobertura && mvn checkstyle:check spotbugs:check
  - cd ../encontre && mvn clean test verify -P cobertura && mvn checkstyle:check spotbugs:check
 
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - openjdk11
